### ISSUE TITLE
Ability to extend participants list

### ISSUE THREAD

**Issue by feistdaniel** [Carq/metting-meter#3]
It would be good to have feature to extend participants list.

**Comment by Carq** [comment]
Hi @feistdaniel 💪🏼
The second request in the same day, application is getting popular 😝🚀
I'd love to add this feature, especially for guy like you 😎

I think I am able to do this during the next weekend 💪🏼

The project is open source, so please do not hesitate to contribute. Of course, if you find a few minutes ^_^

**Comment by Carq** [comment]
@feistdaniel done, HF ;) 

![image](https://user-images.githubusercontent.com/12174774/151656688-31c75235-dac5-4a34-95a1-16ba0d957e37.png)
